### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by maasencioh** [mljs/solver#2]
What it's the intention of this repo? If we're going to maintain this at least should have some description in the readme

cc @andcastillo @JeffersonH44

**Comment by maasencioh** [comment]
ping @andcastillo @JeffersonH44

**Comment by andcastillo** [comment]
We should get out the solution of system of linear equations that is already done in ml-matrix. But the other methods has be reviewed and documented. It was the first @JeffersonH44's project
